In [1]:
import yfinance as yf
stock = yf.Ticker('FB')
df = stock.history(period='max')
#df = stock.history(start='2020-01-01', end='2020-09-15')

In [2]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [4]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2012-05-18,42.05,45.00,38.00,38.23,573576400,0,0
2012-05-21,36.53,36.66,33.00,34.03,168192700,0,0
2012-05-22,32.61,33.59,30.94,31.00,101786600,0,0
2012-05-23,31.37,32.50,31.36,32.00,73600000,0,0
2012-05-24,32.95,33.21,31.77,33.03,50237200,0,0
...,...,...,...,...,...,...,...
2020-09-15,270.67,274.52,269.30,272.42,18478500,0,0
2020-09-16,267.29,272.44,261.79,263.52,29183400,0,0
2020-09-17,258.28,261.50,250.19,254.82,31281400,0,0


In [7]:
print(df.iloc[2,3]) # implicit indexing 
print(df.loc['2012-05-22','Close']) # explict indexing 

31.0
31.0


In [10]:
print(df.iloc[2:4,1:4]) # 끝점 미포함 
print()
print(df.loc['2012-05-22':'2012-05-24','High':'Volume']) # 끝점 포함  

             High    Low  Close
Date                           
2012-05-22  33.59  30.94   31.0
2012-05-23  32.50  31.36   32.0

             High    Low  Close     Volume
Date                                      
2012-05-22  33.59  30.94  31.00  101786600
2012-05-23  32.50  31.36  32.00   73600000
2012-05-24  33.21  31.77  33.03   50237200


In [18]:
print(df.iloc[2,1]) 
print()
print(df.iloc[2:3,1]) 
print()
print(df.iloc[2,1:2]) 
print()
print(df.iloc[2:3,1:2]) 

33.59

[33.59]

[33.59]

[[33.59]]


In [ ]:
a.ijefoiqjwero # 변수 --- 베리어블 
a.zdfvladjf() # 함수 -- 메쏘드

In [22]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape) # 변수 --- 베리어블 
print(a.T) # 변수 --- 베리어블 
print(a.reshape((3,2))) # 함수 -- 메쏘드

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]


In [36]:
df['Close'].shape

(2099,)

In [37]:
df.Close.shape

(2099,)

In [38]:
df[['Close']].shape

(2099, 1)

In [39]:
df[['Open','High','Low','Close']].shape

(2099, 4)

In [43]:
df.loc['2012-05-21']

Open            3.653000e+01
High            3.666000e+01
Low             3.300000e+01
Close           3.403000e+01
Volume          1.681927e+08
Dividends       0.000000e+00
Stock Splits    0.000000e+00
Name: 2012-05-21 00:00:00, dtype: float64

In [44]:
df.loc['2012-05-21',:]

Open            3.653000e+01
High            3.666000e+01
Low             3.300000e+01
Close           3.403000e+01
Volume          1.681927e+08
Dividends       0.000000e+00
Stock Splits    0.000000e+00
Name: 2012-05-21 00:00:00, dtype: float64